[[headers]]
  for = "/assets/**/*.webp"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/**/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/css/*.css"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/js/*.js"
    [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
